FORMAT: 1A
HOST: http://polls.apiblueprint.org/

# Movie API

영화 정보를 제공하는 API 입니다. 수정

# Group Movie

## Movie Collection [/movies]

### All Movies [GET /movies]

+ Response 200 (application/json)

        [
            {
                "id": "m1",
                "title": "The Graduate",
                "year": "1967",
                "genre": "Comedy"
            },
            {
                "id": "m1",
                "title": "The Graduate",
                "year": "1967",
                "genre": "Comedy"
            }
        ]

### Movie [GET /movies/{id}]
+ Parameters
    - id : m1 (string, required)
    
+ Request
    + Header
            
            Authorization : Basic AAA

+ Response 200 (application/json)
    + Attributes
        - id : m1
        - title : The Graduate
        - year : 2016
        - genre : Comedy, Action
        - Include MovieDetail
        - cast (array[Cast])

# Group Movie Anlaytics



# Data Structure

## Cast (object)
- name : test (string, required)
- characterName : test
- birthday : 1970-01-01

## MovieDetail (object)
- rating : 10
- releaseDate : 1980-01-01
- runtime : 100 min
- writers : writer1
- director : 111